### ISSUE TITLE
Problem med sletting av filer i teardown() ved parallell kjøring

### ISSUE THREAD

**Issue by emyklebost** [navikt/kafka-embedded-env#20]
Har flere uavhengige tester som setter opp sin egen KafkaEnvironment og rydder opp vha. teardown().
Teardown() prøver [rekursivt å slette](https://github.com/navikt/kafka-embedded-env/blob/1b781d4b89ba01e93dcca480119dad7faa2fc6f7/src/main/kotlin/no/nav/common/KafkaEnvironment.kt#L269) zookeeper og broker mappene i temp som resulterer i problemer fordi første teardown() prøver å slette andre  KafkaEnvironments sine temp-data.

Gir følgende stacktrace på windows:
```
C:\Users\eirik\AppData\Local\Temp\inmemoryzookeeper\9e7e1ad6-8b69-4040-b4d1-dcc2125cf0c8\version-2\log.1: The process cannot access the file because it is being used by another process
java.nio.file.FileSystemException: C:\Users\eirik\AppData\Local\Temp\inmemoryzookeeper\9e7e1ad6-8b69-4040-b4d1-dcc2125cf0c8\version-2\log.1: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1146)
	at no.nav.common.embeddedutils.FunctionsKt$deleteDir$1.accept(functions.kt:20)
	at no.nav.common.embeddedutils.FunctionsKt$deleteDir$1.accept(functions.kt)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at no.nav.common.embeddedutils.FunctionsKt.deleteDir(functions.kt:20)
	at no.nav.common.KafkaEnvironment.tearDown(KafkaEnvironment.kt:269)
	at e2e.EmbeddedKafka.shutdown(EmbeddedKafka.kt:38)
	at e2e.AppTest.teardown(AppTest.kt:40)
        .....
```

**Comment by MikAoJk** [comment]
Virker som om den er veldig lik denne: https://github.com/navikt/kafka-embedded-env/issues/9

**Comment by MikAoJk** [comment]
https://github.com/navikt/kafka-embedded-env/pull/21

**Comment by MikAoJk** [comment]
@emyklebost Har du mulighet til å se om dette fremdeles er gjeldende?

**Comment by oysbak** [comment]
Stenger denne siden den er gammel og koden er endret mye siden oktober 2021
